name: T-Nexus
description: $description
version: '${version}'

main: network.tserver.tnexus.TNexus
api-version: '26.1.2'
load: POSTWORLD

authors: [ "T_BanGDreamer" ]
website: https://tserver.network

depend:
  - Vault
  - LuckPerms
  - Multiverse-Core
  - FastAsyncWorldEdit

commands:
  tnexus:
    description: T-Nexus main command
    usage: "/<command> [help|reload|version]"
    aliases: [tn, nexus]

permissions:
  tnexus.use:
    description: Allows use of the main T-Nexus command
    default: true
  tnexus.admin:
    description: Allows reloading T-Nexus configuration
    default: op
