name: T-Nexus
description: $description
version: '${version}'

main: network.tserver.tnexus.TNexus
api-version: '26.1.2'
load: POSTWORLD

authors: [ "T_BanGDreamer" ]
website: https://tserver.network

dependencies:
  server:
    Vault:
      load: BEFORE
      required: true
    LuckPerms:
      load: BEFORE
      required: true
    Multiverse-Core:
      load: BEFORE
      required: true
    FastAsyncWorldEdit:
      load: BEFORE
      required: true

commands:
  tnexus:
    description: T-Nexus main command
    usage: "/<command> [help|reload|version]"
    aliases: [tn, nexus]
  balance:
    description: Show your balance
    usage: "/<command> [add|set|take <player> <amount>]"
  bal:
    description: Show your balance
    usage: "/<command> [add|set|take <player> <amount>]"
  pay:
    description: Pay another player
    usage: "/<command> <player>"
  shop:
    description: Manage sign shops
    usage: "/<command> linkitem"
  shops:
    description: List player shops
    usage: "/<command> [player]"
  history:
    description: Open audit history
    usage: "/<command> [player]"

permissions:
  tnexus.use:
    description: Allows use of the main T-Nexus command
    default: true
  tnexus.admin:
    description: Allows reloading T-Nexus configuration
    default: op
  tnexus.shop.use:
    description: Allows using SignShops and management commands
    default: true
  tnexus.shop.player:
    description: Allows creating and managing personal SignShops
    default: true
  tnexus.shop.admin:
    description: Allows editing and removing all SignShops
    default: op
  tnexus.audit.admin:
    description: Allows viewing other players audit history
    default: op
  tnexus.admin.balance:
    description: Allows administrating player balances
    default: op
  tnexus.shop.bypass.ban:
    description: Allows creating banned-material SignShops
    default: op
