CREATE TABLE IF NOT EXISTS ${table_prefix}shops (
    id BIGINT NOT NULL AUTO_INCREMENT,
    shop_type VARCHAR(32) NOT NULL,
    owner_uuid VARCHAR(36) NOT NULL,
    owner_name VARCHAR(64) NOT NULL,
    sign_world VARCHAR(64) NOT NULL,
    sign_x INT NOT NULL,
    sign_y INT NOT NULL,
    sign_z INT NOT NULL,
    chest_world VARCHAR(64) NULL,
    chest_x INT NULL,
    chest_y INT NULL,
    chest_z INT NULL,
    item_stack LONGTEXT NULL,
    item_name VARCHAR(255) NOT NULL,
    buy_price DOUBLE NULL,
    sell_price DOUBLE NULL,
    note VARCHAR(255) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    UNIQUE KEY uq_${table_prefix}shops_sign (sign_world, sign_x, sign_y, sign_z)
);
